source 'https://github.com/CocoaPods/Specs.git'

platform :ios, ‘8.0’
inhibit_all_warnings!

target 'EffectiveCodesDemo' do
  pod 'Bugly'
  pod 'JSPatchPlatform', '~> 1.6.2'
  pod 'FMDB', '~> 2.6.2'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'SDWebImage', '~> 3.8.2'
  pod 'Masonry', '~> 1.0.2'
end



